baseURL: "http://xugr.me/GoMDL"
relativeURLS: true
canonifyURLs: false
title: "Cerulean"
theme: "GoMDL"
permalinks:
  post: /post/:year/:month/:title/
  page: /:filename/
taxonomies:
  tag: "tags"
preserveTaxonomyNames: true
Paginate: 9
buildFuture: True

menu:
  main:
      - Name: "Home"
        Weight: 1
        Identifier: "home"
        URL: ""
      - Name: "Tags"
        Identifier: "tags"
        Weight: 2
        URL: "tags"
      - Name: "Resume"
        Identifier: "resume"
        Weight: 3
        URL: "resume"
      - Name: "About"
        Identifier: "about"
        Weight: 4
        URL: "about"


params:
  Disqus: "megrxu"
  AuthorName: "Ray Xu"
  AvatarURL: "/img/avatar.jpg"
  Footnote: "Built with ❤"
  # Primary Color - Accent-Color
  Theme: "indigo-blue"
  Highlight: "solarized-dark"