baseURL: "https://xugr.me"
title: "Cerulean"
footnoteReturnLinkContents: "↩"
theme: "GoMDL"
permalinks:
  post: /post/:year/:month/:title/
  page: /:filename/
hasCJKLanguage: true
taxonomies:
  tag: "tags"
preserveTaxonomyNames: true
Paginate: 9
buildFuture: True

menu:
  main:
      - Name: "Home"
        Weight: 1
        Identifier: "home"
        URL: "/"
      - Name: "Tags"
        Identifier: "tags"
        Weight: 2
        URL: "/tags/"
      - Name: "Resume"
        Identifier: "resume"
        Weight: 3
        URL: "/resume/"
      - Name: "About"
        Identifier: "about"
        Weight: 4
        URL: "/about/"


params:
  Disqus: "megrxu"
  AuthorName: "Ray Xu"
  AvatarURL: "/img/avatar.jpg"
  Footnote: "Built with ❤"
  highlight: "solarized-dark"